name: Pull Request
description: Template for pull requests

body:
  - type: markdown
    attributes:
      value: |
        ## Pull Request

        Please ensure your pull request adheres to the following guidelines:

  - type: input
    id: title
    attributes:
      label: PR Title
      description: Please provide a clear title for your pull request.
      placeholder: "[TITLE] - "

  - type: textarea
    id: description
    attributes:
      label: PR Description
      description: Provide a clear and concise description of what your pull request does.
      placeholder: "Describe the changes in detail..."

  - type: input
    id: related_issue
    attributes:
      label: Related Issue
      description: If applicable, reference the issue that this PR addresses. Format: Fixes #[issue number]
      placeholder: "Fixes #123"

  - type: textarea
    id: changes_made
    attributes:
      label: Changes Made
      description: List out the changes you made in this PR.
      placeholder: "- Change 1\n- Change 2"

  - type: textarea
    id: how_to_test
    attributes:
      label: How to Test
      description: Provide instructions on how to test the changes made in this PR.
      placeholder: "Instructions..."

  - type: input
    id: demo_link
    attributes:
      label: Demo Link
      description: Link to a demo video or GIF of your changes in action.
      placeholder: "https://link-to-your-demo-video"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the pull request, such as screenshots or additional notes.
      placeholder: "Additional context..."

