name: Masterpiece-Exhibits Feature Request
description: Create a new Feature Request for Masterpiece-Exhibits
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to properly describe the new feature you are suggesting.

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      placeholder: |
        A brief description of your idea

  - type: textarea
    id: goals
    validations:
      required: true
    attributes:
      label: Goals
      description: List the goals of the feature.
      placeholder: |
        - Goal 1
        - Goal 2

  - type: textarea
    id: implementation-details
    validations:
      required: true
    attributes:
      label: Implementation Details
      description: List any technical details about the proposed implementation, including any specific technologies that will be used.
      placeholder: |
        - Implementation Detail 1
        - Implementation Detail 2
        - also add images is possible

  - type: dropdown
    id: skills-required
    attributes:
      label: Tech Skills Needed
      description: Select the technologies needed for this ticket (use Ctrl or Command to select multiple)
      multiple: true
      options:
        - .NET
        - Agile
        - Angular
        - Artificial Intelligence
        - ASP.NET
        - AWS
        - Babel
        - Bootstrap
        - C#
        - Chart.js
        - CI/CD
        - Computer Vision
        - CORS
        - cURL
        - Cypress
        - D3.js
        - Database
        - Debugging
        - Design
        - DevOps
        - Django
        - Docker
        - Electron
        - ESLint
        - Express.js
        - Feature
        - Flask
        - Go
        - GraphQL
        - HTML
        - Ionic
        - Jest
        - Java
        - JavaScript
        - Jenkins
        - JWT
        - Kubernetes
        - Laravel
        - Machine Learning
        - Maintenance
        - Material-UI
        - Microservices
        - MongoDB
        - Mobile
        - Mockups
        - Mocha
        - Natural Language Processing
        - NestJS
        - Node.js
        - NUnit
        - OAuth
        - Performance Improvement
        - Prettier
        - Python
        - Question
        - React
        - React Native
        - Redux
        - RESTful APIs
        - Ruby
        - Ruby on Rails
        - Rust
        - Scala
        - Security
        - Selenium
        - SEO
        - Serverless
        - Solidity
        - Spring Boot
        - SQL
        - Swagger
        - Tailwind CSS
        - Test
        - Testing Library
        - Three.js
        - TypeScript
        - UI/UX/Design
        - Virtual Reality
        - Vue.js
        - WebSockets
        - Webpack
        - Other
    validations:
      required: true

  - type: dropdown
    id: ticket-complexity
    attributes: 
      label: Complexity
      description: Choose a complexity describing the complexity of your ticket
      multiple: false
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: dropdown
    id: category
    attributes: 
      label: Category
      description: Choose the categories that best describe your ticket
      multiple: true
      options:
        - API
        - Backend
        - Database
        - Documentation
        - Deployment
        - Frontend
        - Testing
        - UI
        - UX
        - Other
    validations:
      required: true

  
